//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotels
    {
        public Hotels()
        {
            this.Sejours = new HashSet<Sejours>();
            this.Promotions = new HashSet<Promotions>();
            this.HotelTracking = new HashSet<HotelTracking>();
        }
    
        public int IdHotel { get; set; }
        public string Nom { get; set; }
        public Nullable<int> IdVille { get; set; }
        public Nullable<byte> Categorie { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<Sejours> Sejours { get; set; }
        public virtual Villes Villes { get; set; }
        public virtual ICollection<Promotions> Promotions { get; set; }
        public virtual ICollection<HotelTracking> HotelTracking { get; set; }
    }
}
