//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produits
    {
        public Produits()
        {
            this.Reservations = new HashSet<Reservations>();
        }
    
        public int IdProduit { get; set; }
        public int IdSejour { get; set; }
        public int NbPlaces { get; set; }
        public System.DateTime DateDepart { get; set; }
        public Nullable<decimal> Prix { get; set; }
    
        public virtual Sejours Sejours { get; set; }
        public virtual ICollection<Reservations> Reservations { get; set; }
    }
}
