//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int IdReservation { get; set; }
        public int IdProduit { get; set; }
        public int Quantity { get; set; }
        public int IdUtilisateur { get; set; }
    
        public virtual Produits Produits { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
