//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sejours
    {
        public Sejours()
        {
            this.Produits = new HashSet<Produits>();
        }
    
        public int IdSejour { get; set; }
        public int IdHotel { get; set; }
        public byte Duree { get; set; }
    
        public virtual Hotels Hotels { get; set; }
        public virtual ICollection<Produits> Produits { get; set; }
    }
}
