//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateurs
    {
        public Utilisateurs()
        {
            this.Reservations = new HashSet<Reservations>();
        }
    
        public int IdUtilisateur { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Telephone { get; set; }
        public string IdAspNetUsers { get; set; }
    
        public virtual ICollection<Reservations> Reservations { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
