//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Villes
    {
        public Villes()
        {
            this.Hotels = new HashSet<Hotels>();
        }
    
        public int idVille { get; set; }
        public string name { get; set; }
        public string CodeIso3 { get; set; }
        public string district { get; set; }
        public int population { get; set; }
        public short isCapital { get; set; }
    
        public virtual ICollection<Hotels> Hotels { get; set; }
        public virtual Pays Pays { get; set; }
    }
}
